name: Verification
on:
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

      - name: set up JDK 17
        uses: actions/setup-java@v1
        with:
          java-version: 17

      - name: Unit Test
        run: ./gradlew testDebugUnitTest
        continue-on-error: false

      - name: Run Lint
        run: ./gradlew lint
        continue-on-error: false

      - name: Run Detekt
        run: ./gradlew detekt
        continue-on-error: false